src/chart.zoom.js
Use wheel event instead of deprecated/non-standard mouse wheel event.  Fixes zoom in Firefox.
https://developer.mozilla.org/en-US/docs/Web/Events/wheel
https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel
=> Use wheel event instead of mouse wheel event

src/chart.zoom.js
Pull request #11 reversed the zoom direction.  Here's the fix.
Plus added missing dot to zoom function declaration.
=> Fix zoom direction

samples/zoom.html, src/chart.zoom.js
A `click` event was emitted at the end of the `pan` gesture. This suppresses the click which originates from the `mouseup`, but allows it if the user did not drag the mouse. This is comparable to how [d3-drag](https://github.com/d3/d3-drag) behaves.
=> Suppress ghost click after panning

README.md, src/chart.zoom.js
I added two functions for enforcing the limits and ensured they are called by all zoom/pan functions.
To support both x and y directions, I supplied the detected direction with the options object before passing it along.
The solutions works excellently in my case with a horizontal timescale graph, but I haven't tested it with other scale types, but in theory it should handle that too as it is.
The README.MD file was updated to include the new range settings.
Hope you find this useful - let me know if you have any questions :)
=> Added support for setting lower/upper limit for zoom/pan range

chartjs-plugin-zoom.js
This 2 additional checks are here to fixes the issue #77 that occurs when you load the chartjs-zoom plugin and choose to not apply it to every chart on the page, then the 'wheel' event listener will still listen for all charts, preventing for a normal scroll behaviour on charts.
Thanks for merging ASAP !
=)
=> Should not listen for 'wheel' event if zoom is not enabled.

src/chart.zoom.js
Currently, always the plugin catches events. It should be skipped when zoom is not enabled.
=> Stop event listening when zoom is not enabled

src/chart.zoom.js
scale.firstTick and lastTick are not longer available in latest Chart.js releases. So change to using min and max values for pan/zoom calculations.
=> Fix for zoom and pan on time axis

chartjs-plugin-zoom.js
When pan was did to right side and maxIndex was reached minindex was changed anyway. Same for left side for minIndex.
=> Fix pan index zooming.

src/chart.zoom.js
The center point used for pinch isn't competely correct when the chart is not aligned left.
For wheel event a correction is made using getBoundingClientRect().
I copied the code to the function `handlePinch` and it was working perfectly fine in my use case.
This should close #93 
Best wishes
MeisterLampe
=> Fix pinch center calculation closes #93

README.md, src/chart.zoom.js
Hi,
This PR adds options to customize drag-to-zoom rectangle area:
```js
{
zoom: {
drag: {
borderColor: 'rgba(225,225,225,0.3)'
borderWidth: 5,
backgroundColor: 'rgb(225,225,225)'
}
}
}
```
Closes #106
=> Add options to customize drag-to-zoom area

src/chart.zoom.js
Add the `mouseup` listener on the document rather than on the chart element.
Fix #149
=> Fix mouseup outside chart element

src/plugin.js
@Techn1x is proposing to expose some of these parameters to users in https://github.com/chartjs/chartjs-plugin-zoom/pull/178, so I wanted to make sure they were well understood and documented. I think some of the parameter names were unclear before
=> Add jsdoc for doZoom

samples/zoom-time.html, src/plugin.js
Closes #176 
This PR allows switching between wheel/drag modes of the zoom (if `options.zoom.drag` is changed, it will be taken into account in next events).
- All event listeners are set up in the `beforeInit` method, and the `options.zoom.drag` setting is checked in the body of these listeners rather than at the initialization.
- I added a `Enable/disable drag mode` in the `zoom-time` sample to test this improvement.
- I also fixed the `Reset Zoom` button in the `zoom-time` sample.
=> Allow switching between wheel/drag modes of the zoom

samples/pan-bar.html, src/plugin.js
Solution suggested at https://github.com/chartjs/chartjs-plugin-zoom/issues/60#issuecomment-322501541. I included a little bit of other cleanup I came across related to category scale as well
A couple people on that thread tested and I've now tested as well
Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/60 https://github.com/chartjs/chartjs-plugin-zoom/pull/136
=> Fix pan on category scale when offsetGridLines=false

src/plugin.js
Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/132
Also allows you to turn on zoom if it's not when the chart is originally rendered
=> Ensure pan works when zoom is disabled

samples/zoom-time.html, src/plugin.js
Fixes https://github.com/chartjs/chartjs-plugin-zoom/issues/61
I tested this fix manually against `zoom-time.html` 
I'm guessing the reason it works now but the code was originally required is because the code no longer does `JSON.parse(JSON.stringify(scale.options))` and now does `helpers.clone` instead:
https://github.com/chartjs/chartjs-plugin-zoom/blob/f779867fe2dc2aa66bbdc0959df664dda9461b69/src/plugin.js#L329
=> Don't delete dataset._meta

src/plugin.js
Fixes #197 
With introducing a new data structure `originalOptions`, the scale options can be stored and recalled to reset the zooming/panning.
=> Store original scale options to resetZoom properly

samples/zoom-time.html, src/plugin.js
Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/187
It looks like the wrong variable was being passed to `rangeMinLimiter` and `rangeMaxLimiter` for the time scale. This fixes it by sharing the logic for the numerical scale
=> Share zoom logic between time and numerical scales

README.md, samples/zoom-time.html, src/plugin.js
This PR adds a `speed` option for `zoom`. This option allows to configure the percentage of zoom applied on a wheel event.
Closes #50
=> Add speed option

src/plugin.js
Check if event is cancelable before 'preventDefault' and 'stopImmediatePropagation' calls to prevent following error:
```
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```
Found the solution at: https://stackoverflow.com/questions/26478267/touch-move-getting-stuck-ignored-attempt-to-cancel-a-touchmove
=> prevent interventions

src/plugin.js
Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/205
=> Fix calculation of dragDistance for click

src/plugin.js
Don't calculate unnecessary values when `dragDistanceX <= 0 && dragDistanceY <= 0`
=> Minor optimization for _mouseUpHandler

src/plugin.js
Closes https://github.com/chartjs/chartjs-plugin-zoom/pull/244 https://github.com/chartjs/chartjs-plugin-zoom/pull/196 https://github.com/chartjs/chartjs-plugin-zoom/issues/176 https://github.com/chartjs/chartjs-plugin-zoom/issues/77
=> Fix listener setup

README.md
=> Fixing README to make it directly usable

src/plugin.js
This is an attempt to fix #265 by adding a call to `onZoomComplete()` in `handlePinch()` function.
Quickly tested on Android emulator.
=> Fix #265 - trigger onZoomComplete() on pinch

README.md, src/plugin.js
Allow using a function for `mode` that takes the chart and returns the directions available to scroll. This allows disabling a scrollable x or y direction based on application state instead of a static option.
Fixes #257. Feedback taken from #246
=> Allow using a function for `mode`

README.md, samples/pan-bar.html, samples/zoom-bar-x.html, samples/zoom-bar.html, samples/zoom-horizontal-bar.html, samples/zoom-log.html, samples/zoom-time.html, samples/zoom.html
This PR updates the `Chart.js` version in the README and in the samples.
=> Use Chart.js 2.9.1 in README and samples

src/plugin.js
This corrects two functions in chartjs-plugin-zoom that are using deprecated calls which are removed in git master for chartjs v3.0.
This is my first pull request... please excuse any errors.
=> Fix for chartjs v3.0 deprecated functions

src/plugin.js
Fix for Issue #280 by only using the time options if they are configured by the chart. This will enable backward compatibility while resolving the deprecation warnings for time axis charts with Chart JS 2.9.1.
Note: If the code calling the chart is still using time.min or time.max with Chart JS 2.9.1, it will continue to log deprecation warnings. This will ensure the chart still works.
=> Fix #280 - Deprecation warning with Chart JS 2.9.1

README.md, samples/zoom-time.html, src/plugin.js
The zoom applied when dragging is a bit "abrupt" and it would be nice if we could have an animation in order to have a smoother effect. So this PR add an `animationDuration` option in the `drag` object:
```js
drag: {
animationDuration: 1000
},
```
I also updated the `zoom-time` sample in order to show a demo of this option.
=> Add a `animationDuration` option to configure the duration of the drag animation

src/plugin.js
I believe this mistake doesn't generate a bug, because `typeof chart.options.pan !== 'undefined'` is always true due to `chart.options.pan` has a default value. But for having a clear code i think we should correct it.
=> checking the existance of zoom instead of pan option

src/plugin.js
Zoom does not work as intended in Firefox since the wheel event will sometimes fire without the delta properties.
Closes #337
=> fix zoom not working as intended in Firefox

src/plugin.js
In the previous change I made to the repository I forgot to change the if statement after applying the proposed changes.
In the pull request I included a new if statement which I was asked to reverse. While I did change the code which was executed, I did not change the if-Statement.
I am truly sorry for this mistake.
Previous PR (#338)
Comment by @benmccann proposing the changes (https://github.com/chartjs/chartjs-plugin-zoom/pull/338#issuecomment-609907513)
=> fix bug introduced in #338 (If-statement not reversed)

src/plugin.js
Allows the plugin to work in IE11 without adding babel, etc.
=> Avoid ES6 syntax

src/plugin.js
On chartjs-plugin-zoom.js
493:37  warning  Unexpected mix of '&&' and '||'  no-mixed-operators
493:63  warning  Unexpected mix of '&&' and '||'  no-mixed-operators
✖ 2 problems (0 errors, 2 warnings)
=> Fix no-mixed-operators lint warnings

README.md, package-lock.json, package.json, samples/pan-bar.html, samples/zoom-bar-x.html, samples/zoom-bar.html, samples/zoom-horizontal-bar.html, samples/zoom-log.html, samples/zoom-time.html, samples/zoom.html, src/plugin.js, test/specs/defaults.spec.js
Fixes #406, adapting the plugin to Charts.js 3.0.0-beta7
=> Compatible with Chart.js 3.0.0-beta7

src/plugin.js
When pinching (normally on mobile devices), currently the `onZoomComplete` callback is being called continuously while pinching. This PR ensures `onZoom` is called continuously while pinching and `onZoomComplete` is called when pinch ends.
I believe the problem (as well as the feature itself) has been introduced with #269.
This should fix the problem reported in #305.
=> Properly call onZoom & onZoomComplete when pinching

samples/zoom.html, src/plugin.js
Fixes #409 using `start` and `stop` plugin hooks instead of `beforeInit`, `afterInit` and `destroy`.
=> Use `start` and `stop` plugin hooks instead of `beforeInit`, `afterInit` and `destroy`

.travis.yml
I setup GitHub Actions in https://github.com/chartjs/chartjs-plugin-zoom/pull/402, but was too hasty in removing the `.travis.yml` file. We still need it for releases
=> Restore .travis.yml

.gitignore, gulpfile.js, karma.conf.js, package.json, rollup.config.js, src/index.esm.js, src/index.js, src/plugin.js
Based off of chartjs-plugin-annotation's approach.
Specific changes:
- Switch from Gulp to Rollup for build; using Rollup directly works and seems simpler.
- Refactor some duplicate configuration in rollup.config.js.
- Change import style for Chart.js and Chart.js helpers so that it will work with modules.
- The new import style doesn't allow adding to the imported object, which caused problems for the `Chart.Zoom` namespace. Since that namespace appears to be undocumented and unused, I removed it.
The ESM version does not automatically register the plugin.  This matches chartjs-plugin-annotation and seems to better match Chart.js 3's tree-shaking design.
I'm unclear on whether the UMD build should automatically register the plugin. Not registering seems to better match Chart.js 3, and …
=> Add an ESM build

samples/pan-bar.html, samples/zoom-bar-x.html, samples/zoom-bar.html, samples/zoom-horizontal-bar.html, samples/zoom-log.html, samples/zoom-time.html, samples/zoom.html
Changes the samples in order to import CHART.JS and HAMMERJS from `node_modules`.
This guarantees that the samples are using the real dependencies of the project.
=> Changes script URLs for chart.js and hammer in order to use node_modules

karma.conf.js, samples/zoom-bar-x.html, src/plugin.js
Category scale with lots of labels zooms really slowly. This makes it work similar with numeric scales.
=> Fix zoom on category scale

README.md, src/plugin.js, test/specs/defaults.spec.js
Often the chart captures scroll events in an undesired way, so this PR makes it possible to set an optional `wheelModifierKey` that must be pressed to activate mouse wheel zoom.
A `modifierKey` can also be set for pan. By default this is only checked when the input comes via mouse, but can be set for touch and other inputs with `requireModifierNonMouse: true`
`zoom.onWheelModifierKeyFailed` is fired when a zoom does not occur because the modifier key is not present (e.g. to allow the consumer to display "Press ctrl to zoom"). A similar `pan.onModifierKeyFailed` is also available.
Although not necessarily the requested fix, it will help with the following issues:
#377, #370, #335, #308 (Actually I see the collaborators offer to accept PRs on this issue there). Not looking any further... …
=> Added optional modifier keys

types/options.d.ts
Reuse types from Chart.js ??
->This might be a good idea cuase chartjs-plugin-zoom is strongly bundled with chartjs?
=> Reuse types from Chart.ts

README.md, samples/zoom-separately.html, src/plugin.js, test/specs/zoom.spec.js
Added the **overScaleMode** option so that you can use zoom and pan separately for each scale when the mouse is over the scale.
Try it: https://codepen.io/lirik90/pen/rNLqMVg
Or watch what is it: https://youtu.be/u3HlB3YX_fs
=> Feature: Zoom each scale separately

README.md, samples/zoom-time.html, src/plugin.js, types/options.d.ts
As explained in #450, I suggest to remove the `animationDuration` option (not working with Chart.js 3) in favor of configuration of the `zoom` transition.
Closes #450
=> Remove animationDuration option

src/core.js, src/scale.types.js
This enables the plugin to work with additional scale types, provided the scale works like a numerical scale.
Real example would be a `timeseries` scale that was not supported.
=> Use fallback configration for scale types

src/hammer.js, src/plugin.js
* split `startHammer` into three parts
* remove the `_ghostClickHandler` that would mask the `click` event on pan end of the canvas
* this must have somehow been inserted before chart event listeners in v2
* add similar logic in `beforeEvent` to mask the `click`
Resolves: #441
=> Refactor startHammer

docs/guide/options.md
Reading the code, I have seen that threshold options for zoom, is initialized to 0:
https://github.com/chartjs/chartjs-plugin-zoom/blob/eded3899c7941b1f3d72a9da5bd705a660a8d14b/src/handlers.js#L82
Therefore I think the default could be document to 0, if I'm not wrong.
=> Changes zoom.threshold default to 0

docs/guide/options.md
The correct option is `wheelModifierKey` for the zoom options
=> Correct zoom modifierKey docs

docs/.vuepress/config.js, docs/samples/api.md, package-lock.json, package.json, src/core.js, src/hammer.js, src/handlers.js, src/index.esm.js, src/plugin.js, src/utils.js, types/index.d.ts, types/options.d.ts, types/tests/exports.ts
* Simplify the `doPan` and `doZoom` interface.
* export doPan, doZoom and resetZoom functions.
* add `pan` and `zoom` functions to chart instance.
* Add sample
*
=> Refactor & export pan and zoom functions

README.md
This PR removes the **_API_** section in the README.
The API documentation is incomplete and can now be found in the documentation website. Also, the link to `zoom-time.html` is outdated.
=> Remove API section in README

src/plugin.js, test/specs/module.spec.js
I'm tying to upgrade [chartjs-plugin-streaming](https://github.com/nagix/chartjs-plugin-streaming) for Chart.js 3.x and chartjs-plugin-zoom 1.x, but the latest code doesn't expose `zoomFunctions` or `panFunctions` which are required to support new scale types. So, this PR adds these internal objects to the plugin object as properties.
=> Expose zoomFunctions and panFunctions for customization

docs/samples/api.md, docs/samples/time.md, docs/scripts/utils.js, src/core.js, src/hammer.js, src/handlers.js, src/index.esm.js, src/plugin.js, src/scale.types.js, types/index.d.ts, types/tests/exports.ts
Resolves #126 
I was about to just document setting the `min` and `max` + `chart.update()` method, but that way you lose the ability to reset zoom to previous value. So concluded its better to have that functionality built-in.
* Add `zoomScale` export and chart instance function
* Add sample usage of `zoomScale`
* Rename exported `doPan` to `pan` and `doZoom` to `zoom` for consistency with instance API.
* Add any transition mode support to all of these methods
* Add augmentation of `UpdateModeEnum` to include `'zoom'`
=> Add zoomScale, rename doPan to pan, doZoom to zoom

src/plugin.js
This PR makes `chart.resetZoom` accept the [`UpdateMode`](https://www.chartjs.org/docs/master/api/enums/updatemodeenum.html) argument so that application developers can control animations when they call it.
=> Make resetZoom accept UpdateMode argument

docs/.vuepress/config.js, docs/samples/click-zoom.md, src/hammer.js
=> Add click-to-zoom example

docs/samples/drag.md, src/handlers.js, src/plugin.js, test/index.js, test/specs/zoom.spec.js
Fixes #134 
Fixes #441 
Resolves #372
=> Drag-to-zoom: filter clicks and pan.modifierKey

docs/.vuepress/config.js, docs/guide/options.md, docs/samples/click-zoom.md, docs/samples/pan-region.md, src/hammer.js, src/handlers.js, src/plugin.js, test/specs/pan.spec.js, test/specs/zoom.spec.js, types/options.d.ts
Closes: #373
Closes: #276
* add onPanStart / onZoomStart handlers, that can return `false` to cancel the action
* add sample for limiting pan start to middle of chart
* add tests
* fix bug when `delta` is undefined
* fix callback typings
=> Add onPanStart and onZoomStart callbacks

types/options.d.ts
- Missing `modifierKey` to `PanOptions`
- Missing `wheelModifierKey` to `ZoomOptions`
=> Add missing modifierKey properties to Options

docs/guide/options.md, docs/guide/usage.md, docs/samples/basic.md, docs/samples/drag/category.md, docs/samples/drag/linear.md, docs/samples/drag/log.md, docs/samples/drag/time.md, docs/samples/drag/timeseries.md, docs/samples/pan-region.md, docs/samples/wheel/category.md, docs/samples/wheel/click-zoom.md, docs/samples/wheel/log.md, docs/samples/wheel/over-scale-mode.md, docs/samples/wheel/time.md, samples/zoom-separately.html, src/hammer.js, src/handlers.js, src/plugin.js, test/fixtures/zoom/category-x.js, test/fixtures/zoom/drag.js, test/fixtures/zoom/zoom-reset.js, test/specs/defaults.spec.js, test/specs/zoom.spec.js, types/options.d.ts, types/tests/exports.ts
Hi,
Here is a PR thats adds the ability to enable both wheel and drag modes at the same time, as suggested in #239. I propose to split the wheel/drag configurations like this:
```js
zoom: {
wheel: {
enabled: true,
speed: 0.1,
modifierKey: null
},
drag: {
enabled: true,
backgroundColor: 'yellow',
borderColor: 'black',
borderWidth: 1,
threshold: 1
},
mode: 'xy',
}
```
`speed`, `threshold`, `wheelModifierKey` (now `wheel.modifierKey`) are moved to their respective configurations, I think that makes clearer that a given option refers to a given mode.
=> Add the ability to enable both wheel and drag modes at the same time

docs/guide/options.md
Removes 'undefined' as default from ZOOM options for wheel, drag and pinch because are not undefined
=> Removes 'undefined' as default because is not undefined

src/handlers.js
Fix #525
The `dragging` was left true and plugin kept rejecting all events to chart after that. The update is needed to remove the rectangle drawn.
=> Fix: drag below threshold left dragging state on

src/hammer.js
Fixes the bug described by @pmbert in #525 
The threshold bug is on drag-zoom, so the main issue in 525 is not fixed by this.
=> Fix: modifierKey is not required to end panning

.gitignore
This is also quite close to the .gitignore from chartjs-plugin-annotation, so it helps bring the various Chart.js projects more in sync.  And it keeps my `.vscode` directory from showing up in Git's list of changes.
=> Add .gitignore from Chart.js

docs/guide/options.md, src/core.js, src/hammer.js, src/scale.types.js, types/options.d.ts
This fixes #522 and #523. I put it together for my own use, so everything's in one branch, but I'm happy to submit as smaller PRs for discussion and review whenever someone's ready to take a look at it.
Thank you.
=> Multi-axis zoom and original zoom limits

docs/.vuepress/config.js, docs/guide/developers.md, types/index.d.ts
This adds type definitions and documentation for zoomFunctions and panFunctions.
Feedback / corrections welcome (especially if I've misunderstood anything about how these are expected to work).
Fixes #169.
=> Documentation and type definitions for zoomFunctions and panFunctions

src/handlers.js
The plugin only removed its event listeners if it could access the chart's canvas.  However, Chart.js clears its canvas before notifying plugins, so this didn't work:
https://github.com/chartjs/Chart.js/blob/v3.3.2/src/core/core.controller.js#L857
I noticed this when I destroyed and recreated a Chart.js object against the same HTML `<canvas>` element; the original chart's event handlers still fired and threw errors because the `getState` object had been removed and no longer had needed information.
To address this, I'm now saving the event listener's target as a custom property on the event listener function; that way, `removeHandler` always knows exactly what the target is.
I also noticed that `mouseUp` was calling `removeHandler` with incorrect parameters, so I fixed it.
=> Fix removing event listeners

src/scale.types.js, test/specs/pan.spec.js
Trying to pan a zero-dimension linear scale results in a `RangeError: minimumFractionDigits value is out of range` when LinearBaseScale tries to format its ticks.
This can happen a couple of ways:
* If a scale is configured with an identical min and max - that seems like a misconfiguration, but Chart.js by itself at least attempts to handle it.
* If the browser window is shrunk enough for the chart area to have 0 dimensions
The problem occurs because panNumericalScale calculates a newMin and newMax of NaN here. This, in turn, is because getDecimalForPixel (used by getValueForPixel) and getPixelForValue return NaN for 0-dimension scales.
Fixes #543
=> Fix errors from zero-dimension scales

docs/samples/wheel/click-zoom.md
Couple of places were still checking for moved options, so the title and border did not reflect the state.
=> Fix click to zoom sample

docs/samples/basic.md, src/core.js, src/plugin.js, src/scale.types.js, types/index.d.ts
Changes:
* new `getZoomLevel` function
* `onZoomComplete` call after `resetZoom`
* rename `chartState` to `state` for consistency
* utilize `valueOrDefault` - this could break something, it is not checking for `null`. @joshkel was there a reason for checking `null`?
=> Add getZoomLevel function

docs/guide/options.md, src/hammer.js, src/handlers.js, src/plugin.js, src/utils.js, test/specs/defaults.spec.js, test/specs/zoom.spec.js, types/options.d.ts
=> Add modifierKey option for drag-to-zoom

src/core.js, src/hammer.js
- On chart init, the getZoomLevel returned `NaN` because there were no original scale limits stored yet.
- The modifier key for drag-to-zoom was looked from the wrong place
=> Fix initial zoom level and pan with drag modifier

src/scale.types.js
Zooming out when hovering over y-axis labels or legend (`position: "right"`) would cause `minPercent` to be negative or past 100%, causing the chart to zoom in instead.
Reproduced with a line chart using dates for the x axis. Plugin settings:
```javascript
{
zoom: {
pan: {
enabled: true,
mode: "x"
},
limits: {
x: {
min: "original",
max: "original",
minRange: 7 * 24 * 60 * 60 * 1000
}
},
zoom: {
wheel: {
enabled: true,
},
pinch: {
enabled: true
},
mode: 'x'
}
}
}
=> Avoid zooming in when zooming out over certain areas of chart

docs/guide/developers.md, src/core.js, src/plugin.js, test/specs/api.spec.js, types/index.d.ts, types/tests/exports.ts
Based on the discussion in #584, this adds a new method, `getInitialScaleBounds` that returns an object mapping scale IDs to {min, max} values.
```js
console.log(chart.getInitialScaleBounds());
// {
//    x: {min: 3, max: 8},
//    y: {min: -10, max: 10}
// }
```
I've added tests and type definitions.  I couldn't see anywhere obvious to document this in the guide, but I think exporting it from `index.d.ts` at least adds some basic type doc stuff, right?
=> Add chart method for getting initial scale bounds

docs/guide/options.md, docs/samples/wheel/over-scale-mode.md, samples/zoom-separately.html, src/core.js, src/hammer.js, src/handlers.js, src/plugin.js, src/utils.js, test/specs/zoom.spec.js, types/options.d.ts
As described at https://github.com/chartjs/chartjs-plugin-zoom/discussions/612, I'd like to allow both regular zooming (to zoom both axes via mouse wheel or pinch on the main chart area) and zooming a specific scale (to zoom only one axis via mouse wheel or pinch over the scale axis), but it seems that `overScaleMode` prevents regular zooming from working.
I would have expected that `mode` control regular zooming, while `overScaleMode` controls scale zooming in particular. For example ("scenario A"):
* `{mode: 'xy', overScaleMode: 'y'}` would mean that zooming over the regular chart scales X and Y, and zooming over the Y axis scales Y.
* `{mode: 'x', overScaleMode: 'y'}` would mean that zooming over the regular chart scales X, and zooming over the Y axis scales Y.
* `{mode: 'xy', …
=> Replace overScaleMode with more flexible scaleMode

src/handlers.js
This makes drag act the same as pan (which is implemented by Hammer.js, which - as far as I can tell - automatically only listens to the left / primary mouse button).
By default, right-click is intercepted by the browser to display a context menu, so this isn't noticeable,  However, if `oncontextmenu` is used to disable that (e.g., to use JS to display a menu instead), then right-click can trigger zoom, which feels strange.
=> Only drag zoom on left mouse button

src/handlers.js
This makes the behavior of drag-to-zoom closer to the browser's standard drag-and-drop behavior.
=> Allow canceling drag-to-zoom on Escape key

src/core.js, src/scale.types.js, test/specs/api.spec.js, test/specs/zoom.spec.js
This PR includes two commits fixing the following edge cases (see #690 for details and demos):
* unexpected `isZoomedOrPanned()` true after `resetZoom` if data changed while zoomed
* jitter on zoom-in with fully constrained limits (like a "locked" axis)
* zoom out against a limit vanishes to a no-op as the focal point approaches the other side of the chart
One remaining concern is that this can affect zooming out from category scales in a potentially unintuitive way; further adjustments may be possible once we decide what the desired behavior is.
Thank you; let me know if you'd like any edits!
=> Handling zoom edge cases (#690)

src/handlers.js
Fixes #726.
The edges of the drag rectangle were calculated incorrectly when the chart is placed inside a shadow BOM (eg. inside a web component). Chart.js itself already has fixes for that (see [Chart.js PRs](https://github.com/chartjs/Chart.js/pulls?q=is%3Apr+shadow+dom)). Its getRelativePosition() function always returns the correct coordinates.
So import and use this function from Chart.js.
=> Fix drag rectangle calculation when inside shadow BOM / WebComponent

package-lock.json, package.json, types/index.d.ts
Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/735
Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/721
Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/731
This enum was changed to a normal enum instead of using const in https://github.com/chartjs/Chart.js/pull/11095, so the type is no longer matching with Chart.js.
=> Modify UpdateModeEnum to not be const

package-lock.json, package.json, src/scale.types.js, test/specs/pan.spec.js
Nonlinear scales failed to resolve "original" within panNumericalScale.
To fix this:
* Resolving "original" within panNumericalScale seemed redundant, when updateRange was already doing it, so I instead moved the logic into updateRange and control it with a new special value for the `zoom` parameter.  (Hopefully the use of a special string like this is acceptable as long as JSDoc calls it out - if I should use another approach, please let me know.)
* This change put updateRange over the configured ESLint complexity limit, so I extracted a new getScaleLimits function to reduce complexity.
Add unit tests, both for this bug and for the preexisting but untested    "original" feature.
I wanted JSDoc + TypeScript checks to help validate and document these changes, but that exposed apparent …
=> Fix "original" scale limits with nonlinear pan

package-lock.json, package.json, types/options.d.ts, types/tests/exports.ts
This required adding @types/hammerjs; see https://stackoverflow.com/a/46011417/25507.
=> More descriptive types for Hammer.js events

src/hammer.js
this simply ensures that the custom `onZoomStart` handler is also executed when zooming is initiated with "pinch".
there seems to be a fair difference in the logic structure between the `handlers.js` and `hammer.js` files, so I tried to keep this in line with what I already saw in `hammer.js` directly.
I did not add any tests for this, though I feel like we probably should.. perhaps one of the repo maintainers could help determine where this test should go? I don't see any others that cover the "pinch" functionality specifically.
this follows on from PR #487, and fixes issues #631 and #790.
=> fix: trigger `onZoomStart` from `pinchStart`

docs/guide/developers.md, src/core.js, src/plugin.js, src/state.js, test/specs/zoom.spec.js, types/index.d.ts
I'd like to ensure that browser click events don't trigger if the user is zooming or panning (similar to how Chart.js prevents its own click events from triggering if the user is zooming or panning). Adding a new `isZoomingOrPanning` method seems like the easiest solution.
=> Add isZoomingOrPanning method

docs/guide/options.md
`When the dragging box is dran on the chart`
`When the dragging box is drawn on the chart`
=> fix: typo in drag options documentation

src/handlers.js
=>  Don't trigger the zoom on legends area

docs/.vuepress/config.js, docs/guide/options.md, docs/samples/drag/linear-ratio.md, src/handlers.js, src/plugin.js, test/specs/zoom.wheel.spec.js
Add optional maintainAspectRatio boolean to drag options, which forces the drag rectangle to same aspect ration with chartArea.
closed: https://github.com/chartjs/chartjs-plugin-zoom/issues/115
=> feat(drag): maintainAspectRatio

src/core.js, test/specs/api.spec.js
=> fix: trigger onZoom from zoomScale

docs/.vuepress/config.js, docs/samples/drag/reject-outside.md, src/hammer.js
=> chore: add sample for rejecting drag start outside chartArea

package-lock.json, package.json
7.0.8 apparently introduces a bug where running in watch mode (`npm run dev`) causes `test/index.js` to be endlessly overwritten: https://github.com/jlmakes/karma-rollup-preprocessor/issues/75
=> Pin karma-rollup-preprocessor to 7.0.7

src/handlers.js, test/specs/zoom.drag.spec.js
I believe this is a better UI, and it also fixes some issues with incorrect zoom ranges when dragging the rectangle outside of the chart area.
To help implement this, I copied the clamp helper function from chartjs-plugin-annotation.
Fixes #895
=> Clamp drag rectangle to chart area

src/handlers.js, test/specs/zoom.drag.spec.js
This is a possible fix for #897. Further testing may be needed.
=> Fix handling at canvas edge

.github/workflows/ci.yml
I noticed the `CI` workflow uses `coverallsapp/github-action@master` but this caused warnings of outdated `node`version
Checking the repo, I found this thread: https://github.com/coverallsapp/github-action/issues/201 which described that they switched from `master` to `main` a year ago (https://github.com/coverallsapp/github-action/issues/201#issuecomment-2234228863).
This PR updated the workflow file to use a tagged version of `coverallsapp` instead of the deprecated `master` branch
=> Switch coverallsapp action to use a  tag version instead of deprecated master branch

src/hammer.js, test/specs/zoom.pinch.spec.js
=> fix: pinch events

src/core.js, src/hammer.js, src/handlers.js, src/state.js, test/specs/api.spec.js, test/specs/zoom.drag.spec.js, test/specs/zoom.wheel.spec.js, types/index.d.ts, types/options.d.ts
Add `trigger` property to the onZoom context object, indication what triggeder the zoom. Possible values: 'api', 'drag', 'wheel', 'pinch'.
=> feat: add trigger to onZoom context

src/core.ts, src/plugin.ts
This revises the logic from #823 to account for changes in #891.
=> Check for filterNextClick in evaluating isZoomingOrPanning

src/hammer.ts, src/state.ts
To fix this, instead of tracking the actual Scale objects, I'm tracking scale IDs.
Fixes #929
=> Handle scales removed while panning
