chartjs/chartjs-plugin-zoom

Chart.Zoom.js
src/chart.zoom.js

Required modules names fix.

---

README.md

Fix configuration comment in README

---

.travis.yml
config.jshintrc
package.json
src/chart.zoom.js

Adds travis CI and fixes JShint issues

Add travis CI & fix JShint issues

---

src/chart.zoom.js

Remove wheel event listener on destroy.

Remove wheel event listener on destroy

---

Chart.Zoom.js

Prevent page scrolling when mouse wheel is triggered over the chart

---

src/chart.zoom.js

Zoom to Mouse Cursor (Draft) as suggested in Issue #21

Zoom to Mouse Cursor and Only pan deltaY on vertical scale fix

---

README.md

Add a link to a live demo of the library in the README

Add link to live demo

---

src/chart.zoom.js

Solves issue #81
https://github.com/chartjs/chartjs-plugin-zoom/issues/81

Solves issue #81 (Zoom is zooming in the wrong direction)

---

src/chart.zoom.js

When both axes are enabled (xy) then fingers can change only x
(horizontal position of fingers), or only y (vertical position of fingers) or both axes
(diagonal position of fingers).

Updated doZoom when handling pinch.

---

src/chart.zoom.js

This bug breaks zooming with mouse wheel.

bugfix: _whichAxes not declared

---

src/chart.zoom.js

The plugin id `'zoom'` is added.

Add plugin ID

---

README.md
src/plugin.js

Knowing how the chart was zoomed or panned will probably be useful information (at least, it was for me).

Added onPan/onZoom args

---

README.md
samples/pan-bar.html
samples/zoom-bar-x.html
samples/zoom-bar.html
samples/zoom-log.html
samples/zoom-time.html
samples/zoom.html

- Removed `limits` from samples. This option doesn't appear to have ever existed as far as I can tell
- Removed todo items from readme. They appear mostly done and there's lots missing. The issue tracker is probably a better place to keep track of this

Improve readme and samples

---

src/plugin.js

Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/140

Fix pan at limits of range

---

src/plugin.js

Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/218
Thanks @ricvec for the suggestion

Missing argument to doZoom

---

src/plugin.js

Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/209

Ensure rangeMin and rangeMax variables are defined

---

README.md
samples/pan-bar.html
samples/zoom-bar-x.html
samples/zoom-bar.html
samples/zoom-horizontal-bar.html
samples/zoom-log.html
samples/zoom-time.html
samples/zoom.html
src/plugin.js

Closes https://github.com/chartjs/chartjs-plugin-zoom/pull/217 & https://github.com/chartjs/chartjs-plugin-zoom/issues/195
FYI @ezpzlmnsqz1337
@simonbrunel pointed out several issues with the plugin's current handling of options in the #dev channel on Slack. This attempts to address those issues in a more holistic manner

Cleanup options handling

---

README.md
package-lock.json
package.json
rollup.config.js
samples/pan-bar.html
samples/zoom-bar-x.html
samples/zoom-bar.html
samples/zoom-horizontal-bar.html
samples/zoom-log.html
samples/zoom-time.html
samples/zoom.html

Release notes here: https://github.com/chartjs/chartjs-plugin-zoom/releases/edit/untagged-cef6534833172b3552b3
@simonbrunel I think you will need to create the release branch for us

Version 0.7.0

---

src/plugin.js

@SosthenG @rajkumar-osm @jdbdnz @jledentu @Skuhoo @etimberg @joseRelvasF3m please help test this risky change
I'm proposing to remove the clipping to fix the problem reported in https://github.com/chartjs/chartjs-plugin-zoom/issues/177 and https://github.com/chartjs/chartjs-plugin-zoom/issues/41. [@SosthenG said it made things worse for him](https://github.com/chartjs/chartjs-plugin-zoom/issues/177#issuecomment-490820730), but I haven't been able to reproduce that, so I'm tempted to move ahead. If that does indeed make things worse in some scenarios, please let me know how to reproduce. Thanks!

Do not clip chart area

---

README.md
src/plugin.js

Updated https://github.com/chartjs/chartjs-plugin-zoom/pull/237 to include zoom as well

Fix #233: onPan function is called multiple times

---

src/plugin.js

Closes https://github.com/chartjs/chartjs-plugin-zoom/issues/181

Additional fixes for listener setup

---

README.md

Add documentation about these properties in README:
* `pan.speed`
* `pan.threshold`
* `zoom.sensitivity`

Add missing properties in README (speed/threshold/sensitivity)

---

README.md
src/plugin.js

This fix prevets zooming by mistake

Add zoom threshold (#317)

---

package.json

This bumps the version in `master`. Then we'll need to merge this to the `release` branch

Release 0.7.6

---

package-lock.json
package.json
types/index.d.ts
types/options.d.ts
types/test/exports.ts
types/test/tsconfig.json

adding typings for chartjs-plugin-zoom analog to chartjs-plugin-annotation

adding typings for Zoom analog to chartjs-plugin-annotation

---

docs/guide/integration.md
docs/guide/options.md

This PR fixes little typo errors in docs.

Fix minor typo errors in docs

---

types/index.d.ts

Add missing return types

---

src/core.js
src/hammer.js

Fix hook parameters

---

docs/guide/options.md
docs/samples/basic.md
docs/samples/log.md
src/core.js
src/hammer.js
src/handlers.js
src/plugin.js
src/scale.types.js
types/index.d.ts
types/options.d.ts
types/tests/exports.ts

Combine range options, add minimum scale range

---

docs/.vuepress/config.js
docs/samples/drag.md

This PR adds a sample in the docs that shows the Drag-To-Zoom behavior.

Add a sample for drag-to-zoom in docs

---

.gitignore
docs/.vuepress/config.js
package-lock.json
package.json
tsconfig.json

Add API documentation (typedoc)

---

src/plugin.js

Fix #298 
I failed to create any good tests for this :/

Cancel all chart events while panning or dragging

---

docs/guide/options.md

Adds drag effect options to the documentation because was missing.

Adds drag effect options to the documentation 

---

docs/samples/wheel/click-zoom.md

Adds note to click zoom sample about the text on top of the chart.

Adds note to click zoom sample

---

src/handlers.js

Fix drag threshold for single axis modes

---

docs/.vuepress/config.js
docs/samples/fetch-data.md

Add fetch-data example

---

types/index.d.ts
types/options.d.ts
types/tests/exports.ts
types/tests/tsconfig.json

Fix strict mode errors from typings

---

src/handlers.js
test/specs/zoom.spec.js

Re-attach event handlers only when needed

---

.github/workflows/publish-npm.yml

Publish latest/next docs in separate job

---

docs/.vuepress/config.js
karma.conf.js
package-lock.json
package.json
test/index.js
tsconfig.json
types/index.d.ts

Resolves https://github.com/chartjs/chartjs-plugin-zoom/issues/694

add-v4-compatibility

---

src/handlers.js

fix: explicit passive: false for wheel events to prevent warnings on console

---

docs/.vuepress/config.js
docs/samples/wheel/category-min-range.md

chore: add sample for minRange on category scale

---

docs/samples/api.md
docs/samples/wheel/log.md
karma.conf.js
src/handlers.js
src/scale.types.js
test/specs/zoom.wheel.spec.js

fix: incorrect zoom out factor when using using wheel

---

src/hammer.js
src/handlers.js
src/plugin.js

fix: filter only one click after drag/pan is completed
